#!/usr/bin/env python3
"""Host-side state collector for the Marlin State Map.

Runs on Gretchen under a systemd user timer. Writes a snapshot of machine
state into the vault, where the cockpit container can read it through its
existing /vault mount.

MACHINE-GENERATED. Regenerated wholesale on every run. Never hand-edit the
output: the State Map's contract (marlin-adr-057) is that everything it
shows is derived, and a hand-edited file it trusts violates that.
"""
import json
import os
import subprocess
from datetime import datetime
from pathlib import Path

GIT_ROOT = Path(os.environ.get("STATEMAP_GIT_ROOT", Path.home() / "git"))
VAULT = Path(os.environ.get("VAULT_PATH", Path.home() / "Documents/Obsidian/Marlin"))
OUT = VAULT / "System" / "StateMap" / "machine.json"
BACKUP_UNIT = os.environ.get("STATEMAP_BACKUP_UNIT", "ivy-backup.service")


def _run(args, cwd=None):
    """Return stdout, or None if the command fails. Never raises: a broken
    repo must not take the whole snapshot down."""
    try:
        out = subprocess.run(args, cwd=cwd, capture_output=True, text=True, timeout=15)
        return out.stdout.strip() if out.returncode == 0 else None
    except (OSError, subprocess.SubprocessError):
        return None


def collect_repos():
    repos = []
    try:
        paths = sorted(GIT_ROOT.iterdir())
    except OSError:
        # GIT_ROOT missing, unmounted, or unreadable: degrade to an empty
        # repos list rather than take the whole snapshot down.
        return repos
    for path in paths:
        # A git worktree's .git is a *file* (pointing at the main repo's
        # gitdir), not a directory — .is_dir() would skip every worktree.
        if not (path / ".git").exists():
            continue
        branch = _run(["git", "branch", "--show-current"], cwd=path)
        last = _run(["git", "log", "-1", "--format=%cs"], cwd=path)
        status = _run(["git", "status", "--porcelain"], cwd=path)
        repos.append({
            "name": path.name,
            "branch": branch,
            "last_commit": last,
            "dirty_files": len(status.splitlines()) if status else 0,
        })
    return repos


def collect_services():
    names = _run(["docker", "ps", "--all", "--format", "{{.Names}}\t{{.State}}"])
    services = []
    for line in (names or "").splitlines():
        name, _, state = line.partition("\t")
        if name:
            services.append({"name": name, "running": state == "running"})
    return services


def collect_backup():
    props = _run(["systemctl", "--user", "show", BACKUP_UNIT,
                  "--property=ExecMainExitTimestamp", "--property=Result"])
    last_run, result = None, None
    for line in (props or "").splitlines():
        key, _, value = line.partition("=")
        if key == "Result":
            result = value or None
        elif key == "ExecMainExitTimestamp" and value:
            # systemd format: "Fri 2026-09-04 00:13:52 PDT"
            parts = value.split()
            if len(parts) >= 3:
                try:
                    last_run = datetime.strptime(" ".join(parts[1:3]),
                                                 "%Y-%m-%d %H:%M:%S").isoformat()
                except ValueError:
                    last_run = None
    return {"unit": BACKUP_UNIT, "last_run": last_run, "result": result}


def main():
    snapshot = {
        "_warning": "MACHINE-GENERATED by statemap/collect.py. Do not hand-edit.",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "repos": collect_repos(),
        "services": collect_services(),
        "backup": collect_backup(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(snapshot, indent=2), encoding="utf-8")
    # Atomic replace: the cockpit polls this file and must never read a
    # half-written snapshot.
    tmp.replace(OUT)
    print(f"[statemap] wrote {OUT} — {len(snapshot['repos'])} repos, "
          f"{len(snapshot['services'])} services")


if __name__ == "__main__":
    main()
